requirements: update hiredis to the latest versions
Without this update the following error is thrown when installing hiredis
with the latest python3 versions:

 +-------------------------------+
 | Digi ConnectCore demo WEB app |
 +-------------------------------+

 Please, wait while the script prepares the virtual environment
 and runs the WEB server...

- Checking project structure... [OK]
- Generating virtual environment... [sudo] password for fgilmar:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3.12-venv is already the newest version (3.12.3-1ubuntu0.7).
The following packages were automatically installed and are no longer required:
  libavahi-compat-libdnssd1 libb2-1 libdouble-conversion3 libmd4c0 libqt5core5t64 libqt5dbus5t64 libqt5gui5t64 libqt5network5t64 libqt5qml5 libqt5qmlmodels5 libqt5quick5 libqt5svg5
  libqt5waylandclient5 libqt5waylandcompositor5 libqt5widgets5t64 libqt6core6t64 libqt6dbus6t64 libqt6gui6t64 libqt6network6t64 libqt6opengl6t64 libqt6qml6 libqt6qmlmodels6
  libqt6quick6 libqt6waylandclient6 libqt6waylandcompositor6 libqt6waylandeglclienthwintegration6 libqt6waylandeglcompositorhwintegration6 libqt6widgets6t64 libqt6wlshellintegration6
  libts0t64 libxcb-xinerama0 libxcb-xinput0 qt5-gtk-platformtheme qt6-gtk-platformtheme qt6-qpa-plugins qt6-translations-l10n qt6-wayland qttranslations5-l10n qtwayland5
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 127 not upgraded.
[OK]
- Installing basic modules... [OK]
- Installing application requirements:
  - Installing module 'aioredis==1.3.1; sys_platform=='linux''... [OK]
  - Installing module 'arrow==1.2.2'... [OK]
  - Installing module 'asgiref==3.5.1'... [OK]
  - Installing module 'async-timeout==4.0.2'... [OK]
  - Installing module 'attrs==21.4.0'... [OK]
  - Installing module 'autobahn==22.4.2'... [OK]
  - Installing module 'Automat==20.2.0'... [OK]
  - Installing module 'backports.functools-lru-cache==1.6.4'... [OK]
  - Installing module 'certifi==2021.10.8'... [OK]
  - Installing module 'cffi==1.15.0'... [OK]
  - Installing module 'channels==3.0.4'... [OK]
  - Installing module 'channels-redis==3.4.0; sys_platform=='linux''... [OK]
  - Installing module 'chardet==4.0.0'... [OK]
  - Installing module 'charset-normalizer==2.0.12'... [OK]
  - Installing module 'constantly==15.1.0'... [OK]
  - Installing module 'cryptography==39.0.0'... [OK]
  - Installing module 'daphne==3.0.2'... [OK]
  - Installing module 'devicecloud==0.5.9'... [OK]
  - Installing module 'Django==4.0.4'... [OK]
  - Installing module 'hiredis==2.0.0; sys_platform=='linux''... Traceback (most recent call last):
  File "/tftpboot/digidotcom-digi-iot-web-apps-511792a/connectcore/run_web_app.py", line 339, in <module>
    main()
  File "/tftpboot/digidotcom-digi-iot-web-apps-511792a/connectcore/run_web_app.py", line 304, in main
    if run_venv_script(venv_context, ['pip', 'install', line],
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tftpboot/digidotcom-digi-iot-web-apps-511792a/connectcore/run_web_app.py", line 151, in run_venv_script
    return subprocess.check_call(command,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tftpboot/digidotcom-digi-iot-web-apps-511792a/connectcore/.venv/bin/pip', 'install', "hiredis==2.0.0; sys_platform=='linux'"]' returned non-zero exit status 1.

Signed-off-by: Francisco Gil <francisco.gilmartinez@digi.com>